esphome:
  name: esp-32-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jrIK1tFbo3T8oTxO37sEVarBfCBubXLMxND2HyFDKs0="

ota:
  password: "1bef0e266163e4d58bf4d1204958199c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32-1 Fallback Hotspot"
    password: "jImTWXizRyDl"

time:
  - platform: homeassistant
    id: homeassistant_time

deep_sleep:
  run_duration: 30min
  sleep_duration: 5min
  id: deep_sleep1

sensor:
  - platform: adc # airdry: 2,8V; waterwet: 1,58V
    pin: A0
    name: "soil Moisture"
    id: moisturesensor2
    attenuation: auto
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 5s
    filters:
    - median:   #median over the last 7 values
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear: #setting the volatge values to equalent percantages
        - 2.75 -> 0.00
        - 1.40 -> 100.00
    # limit the value to 0 and 100%
    - lambda: |-
        if (x < 0) return 0;
        else if (x > 100) return 100;
        else return (x);
    on_value:
      then:
        - if:
            condition:  #check that the threshold value from HA UI is imported
              sensor.in_range:
                id: moisture_set
                below: 100.0
            then:
              - if:
                  condition:  #compare value from sensor with threshold value, it is more complicated that "on_range" bcs it also triggers now when the value didnt changed
                    # lambda: 'return id(moisturesensor2).state < id(moisture_set).state;'
                    lambda: 'return id(moisturesensor2).state < 50;'
                  then:
                  - deep_sleep.prevent: deep_sleep1
                  - switch.turn_on: pump1
                  - switch.turn_on: LED2
                  - delay: 10s
                  - switch.turn_off: pump1
                  - switch.turn_off: LED2
                  - sensor.template.publish: #sending Timestamp of pumping to HA UI                                                                           
                      id: pump1_last_update                                                                                                                   
                      state: !lambda 'return id(homeassistant_time).now().timestamp;'
                  - if:
                      condition: #prevent esp32 from entering deep_sleep for updating purpose
                        binary_sensor.is_on: preventdeepsleep_set
                      then:
                      - deep_sleep.prevent: deep_sleep1
                      else:
                      - deep_sleep.enter:
                          id: deep_sleep1
                          sleep_duration: 2min
                  else:
                  - switch.turn_on: LED2
                  - delay: 5s
                  - switch.turn_off: LED2
                  - if:
                      condition: #prevent esp32 from entering deep_sleep for updating purpose
                        binary_sensor.is_on: preventdeepsleep_set
                      then:
                      - deep_sleep.prevent: deep_sleep1
                      else:
                      - deep_sleep.enter:
                          id: deep_sleep1
                          sleep_duration: !lambda 'return id(sleeptime_set).state*60000;' #for converting in min *60000, for converting in h *3600000

  - platform: homeassistant
    name: "Moisture Set Point"
    entity_id: input_number.desired_moisture1
    id: moisture_set
    accuracy_decimals: 0

  - platform: homeassistant
    name: "Sleep Time"
    entity_id: input_number.desired_sleeptime1
    id: sleeptime_set

  - platform: template
    name: "Pump1 last watered"
    device_class: timestamp
    id: pump1_last_update

binary_sensor:
  - platform: homeassistant
    name: "prevent deep_sleep"
    entity_id: input_boolean.prevent_deep_sleep
    id: preventdeepsleep_set

switch:
  - platform: gpio
    pin: GPIO13
    name: "pumping"
    id: pump1
    restore_mode: ALWAYS_OFF
    icon: "mdi:water-pump"

  - platform: gpio
    pin: GPIO2
    name: "running"
    id: LED2
    inverted: true

captive_portal:
    