esphome:
  name: esp-8266-1

esp8266:
  #board: esp01_1m
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/Xrl74A2ZJkY8sX12F1B5XKz3VOxfS/aUVAMa/tSF7E="

ota:
  password: "ecb03f139ee9d0ec3f053b75df57af9c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-8266-1 Fallback Hotspot"
    password: "UXNSHdpOAJhI"

sensor:
  - platform: adc
    pin: A0
    name: "Sensor 1"
    id: living_room_plant_moisture_sensor
    update_interval: 5s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    state_class: "measurement"
    filters:
      - multiply: 3.3
      - median:   #median over the last 7 values
          window_size: 7
          send_every: 4
          send_first_at: 1
      - calibrate_linear: #setting the volatge values to equivalent percentages
        - 2.80 -> 0.00
        - 1.58 -> 100.00
    # limit the value to 0 and 100%
      - lambda: |-
         if (x < 0) return 0; 
         else if (x > 100) return 100;
         else return (x);
    # unit_of_measurement: "V"

    on_value:
      - if:
          condition:
            sensor.in_range:
              id: living_room_plant_moisture_sensor
              #above: 2.0
              below: 50.0
          then:
          - switch.turn_on: living_room_plant_onboard_led
      - if:
          condition:
            sensor.in_range:
              id: living_room_plant_moisture_sensor
              #below: 2.0
              above: 50.0
          then:
          - switch.turn_off: living_room_plant_onboard_led
          
switch:
  - platform: gpio
    pin: GPIO2
    name: "Led"
    id: living_room_plant_onboard_led
    inverted: "True"

captive_portal:
    