esphome:
  name: plant-sensor-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MC3q9EE41N9VbEcbJ4uvg82GJSwNumZUgJ2yhx7CM8Y="

ota:
  password: "c30cd3ecded53a63e46a1d278a93e996"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant-Sensor-1 Fallback Hotspot"
    password: "FdwGiYI9K5HI"

sensor:
  - platform: adc # airdry: 2.8V; waterwet: 1.29V
    pin: GPIO35
    name: "Plant Moisture Sensor 1"
    id: moisturesensor1
    update_interval: 5s
    attenuation: auto
    unit_of_measurement: "%"
    accuracy_decimals: 0
    state_class: "measurement"
    filters:
    - median:   #median over the last 7 values
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear: #setting the volatge values to equivalent percentages
        - 2.80 -> 0.00
        - 1.58 -> 100.00
    # limit the value to 0 and 100%
    - lambda: |-
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);
    on_value:
      - if:
          condition:
            sensor.in_range:
              #id: moisture_set
              id: moisturesensor1
              below: 50.0
          then:
          - switch.turn_on: led1
      - if:
          condition:
            sensor.in_range:
              id: moisturesensor1
              above: 50.0
          then:
          - switch.turn_off: led1
  
  - platform: homeassistant
    name: "Moisture Set Point"
    entity_id: input_number.slider
    id: moisture_set
    accuracy_decimals: 0

switch:
  - platform: gpio
    pin: GPIO2
    name: "Led"
    id: led1

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "Button"
    id: switch1
    on_press:
      then:
        - switch.toggle: led1

captive_portal:
